CREATE DATABASE IF NOT EXISTS ppm DEFAULT CHARACTER SET utf8mb4;
USE ppm;

CREATE TABLE IF NOT EXISTS `user` (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(50) NOT NULL UNIQUE,
  password_hash VARCHAR(100) NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'USER',
  status VARCHAR(20) NOT NULL DEFAULT 'ENABLED',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_login_at DATETIME NULL,
  deleted TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS project (
  id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(100) NOT NULL, code VARCHAR(50) NOT NULL,
  owner_id BIGINT NOT NULL, sort_no INT NOT NULL DEFAULT 0, description LONGTEXT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0, INDEX idx_owner (owner_id)
);

CREATE TABLE IF NOT EXISTS task (
  id BIGINT PRIMARY KEY AUTO_INCREMENT, title VARCHAR(200) NOT NULL, project_id BIGINT NULL, owner_id BIGINT NOT NULL,
  type VARCHAR(20) NULL, priority VARCHAR(10) NOT NULL DEFAULT 'MEDIUM', status VARCHAR(10) NOT NULL DEFAULT 'TODO',
  plan_start_at DATETIME NULL, due_at DATETIME NULL, description LONGTEXT NULL, finished_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted TINYINT NOT NULL DEFAULT 0,
  INDEX idx_owner (owner_id), INDEX idx_project (project_id), INDEX idx_status (status)
);

CREATE TABLE IF NOT EXISTS task_history (
  id BIGINT PRIMARY KEY AUTO_INCREMENT, task_id BIGINT NOT NULL, user_id BIGINT NULL,
  user_name VARCHAR(50) NULL, action VARCHAR(50) NOT NULL, detail VARCHAR(1000) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_task (task_id)
);

CREATE TABLE IF NOT EXISTS task_note (
  id BIGINT PRIMARY KEY AUTO_INCREMENT, task_id BIGINT NOT NULL, author_id BIGINT NOT NULL,
  author_name VARCHAR(50) NULL, content LONGTEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted TINYINT NOT NULL DEFAULT 0,
  INDEX idx_task (task_id)
);

CREATE TABLE IF NOT EXISTS attachment (
  id BIGINT PRIMARY KEY AUTO_INCREMENT, task_id BIGINT NULL, kind VARCHAR(10) NOT NULL DEFAULT 'FILE',
  file_name VARCHAR(255) NOT NULL, file_path VARCHAR(500) NOT NULL, url VARCHAR(500) NOT NULL,
  size BIGINT NOT NULL DEFAULT 0, mime_type VARCHAR(100) NULL, uploaded_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_task (task_id)
);
